name: build

on:
  push:

env:
  HVCC_VERSION: 424308377a8b0e4291e0bfda3bcf68ae9fd88f33

jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/Wasted-Audio/hvcc.git@${{ env.HVCC_VERSION }}
          sudo apt-get update -qq
          sudo apt-get install -yqq libgl1-mesa-dev

      - name: Build plugins
        run: |
          hvcc wstd_manglr.pd -n WSTD_MANGLR -m wstd_manglr.json -o WSTD_MANGLR -g dpf -p dep/heavylib/ dep/ --copyright "Copyright (c) Wasted Audio 2023 - GPL-3.0-or-later"
          cp override/* WSTD_MANGLR/plugin/source/
          make -C WSTD_MANGLR WITH_LTO=true DEBUG=true -j $(nproc)

      - name: Set sha8 (non-release)
        if: startsWith(github.ref, 'refs/tags/') != true
        id: slug1
        run: echo "action_tag=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
      - name: Set tag (release)
        if: startsWith(github.ref, 'refs/tags/')
        id: slug2
        run: echo "action_tag=$(echo ${{ github.ref_name }})" >> $GITHUB_ENV

      - name: Pack binaries
        run: |
          cd WSTD_MANGLR
          mv bin WSTD_MANGLR
          tar -c -h  -z -f ${{ github.event.repository.name }}-linux-x86_64-${{ github.event.pull_request.number || env.action_tag }}.tar.gz WSTD_MANGLR/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-linux-x86_64-${{ github.event.pull_request.number || env.action_tag }}
          path: |
            WSTD_MANGLR/*.tar.gz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          # files: |
          #   WSTD_MANGLR/*.tar.gz
